from .benefits import *
from .cinema import *
from .feedback_table import *
from .food import *
from .courses import *
from .library import *
from .links import *
from .location_table import *
from .roomfinder import *
from .sport import *
from .time_range_table import *
from .university_table import *
from .user_table import *
from .wishlist import *
