query clubs($languageCode: String!) {
    student_club_categories {
        id
        emoji
        translations(filter: { languages_code: { code: { _eq: $languageCode } } }) {
            title
        }
    }

    student_clubs(sort: ["translations.title"], filter: { is_shown: { _eq: true } }) {
        id
        univerities {
            id
        }
        type
        image: logo {
            title
            id
        }
        url
        email
        instagram_url
        linkedin_url
        category {
            id
        }
        founding_year
        address
        location
        translations(filter: { languages_code: { code: { _eq: $languageCode } } }) {
            title
            description
            content
        }
    }
}
