services:
    db:
        image: postgres:16.4-bookworm
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        container_name: db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_HOST: ${POSTGRES_HOST}
            PGDATABASE: ${POSTGRES_DB}
        ports:
            - '127.0.0.1:5432:5432'
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 2s
            timeout: 2s
            retries: 5
        networks:
            - backend
            - frontend

    db_mb:
        image: postgres:16.4-bookworm
        volumes:
            - postgres_metabase_data:/var/lib/postgresql/data/
        container_name: db_mb
        environment:
            POSTGRES_DB: ${MB_DB_DBNAME}
            POSTGRES_USER: ${MB_DB_USER}
            POSTGRES_PASSWORD: ${MB_DB_PASSWORD}
            POSTGRES_PORT: ${MB_DB_PORT}
            POSTGRES_HOST: ${MB_DB_HOST}
        ports:
            - '5433:5432'
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${MB_DB_USER}']
            interval: 2s
            timeout: 2s
            retries: 5
        networks:
            - backend

    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        hostname: metabase
        volumes:
            - /dev/urandom:/dev/random:ro
        ports:
            - 3000:3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: ${MB_DB_DBNAME}
            MB_DB_PORT: ${MB_DB_PORT}
            MB_DB_USER: ${MB_DB_USER}
            MB_DB_PASS: ${MB_DB_PASSWORD}
            MB_DB_HOST: ${MB_DB_HOST}
        networks:
            - frontend
            - backend
        healthcheck:
            test: curl --fail -I http://localhost:3000/api/health || exit 1
            interval: 15s
            timeout: 5s
            retries: 5
        depends_on:
            db_mb:
                condition: service_healthy
        env_file:
            - .env

    api:
        image: ${DOCKER_USERNAME}/lmu-app-backend-api:${ENVIRONMENT}
        build:
            context: .
            dockerfile: docker/Dockerfile-api
            args:
                BUILD_ENV: ${ENVIRONMENT:-development}
                COMMIT_SHA: local
                BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
        environment:
            - PYTHONPATH=/app
            - ENVIRONMENT=${ENVIRONMENT:-development}
        env_file:
            - .env
        container_name: api
        networks:
            - backend
            - frontend
        ports:
            - '127.0.0.1:8001:8000'
        depends_on:
            db:
                condition: service_healthy
        restart: always

    api_dev:
        extends: api
        container_name: api_dev
        volumes:
            - .:/app

    data_fetcher:
        image: ${DOCKER_USERNAME}/lmu-app-backend-data:${ENVIRONMENT}
        build:
            context: .
            dockerfile: docker/Dockerfile-data_fetcher
            args:
                BUILD_ENV: ${ENVIRONMENT:-development}
                COMMIT_SHA: local
                BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
        env_file:
            - .env
        container_name: data_fetcher
        networks:
            - frontend
            - backend
        environment:
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - ENVIRONMENT=${ENVIRONMENT:-development}
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure

    data_fetcher_dev:
        extends: data_fetcher
        container_name: data_fetcher_dev
        volumes:
            - .:/app

    nginx:
        container_name: nginx
        image: 'jc21/nginx-proxy-manager:2.12.3'
        restart: unless-stopped
        ports:
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
        volumes:
            - ./nginx/data:/data
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./nginx/snippets:/snippets:ro
        environment:
            TZ: 'Europe/Berlin'
        networks:
            - frontend

volumes:
    postgres_data:
    postgres_metabase_data:

networks:
    backend:
        internal: true
    frontend:
        external: true
