services:
    api:
        image: ${DOCKER_USERNAME}/lmu-app-backend-api:${ENVIRONMENT}
        build:
            context: .
            dockerfile: docker/Dockerfile-api
            args:
                BUILD_ENV: ${ENVIRONMENT:-development}
                COMMIT_SHA: local
                BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
        environment:
            - PYTHONPATH=/app
            - ENVIRONMENT=${ENVIRONMENT:-development}
        env_file:
            - .env
        container_name: api
        networks:
            - shared
        ports:
            - '127.0.0.1:8001:8000'

        restart: always

    api_dev:
        extends: api
        container_name: api_dev
        volumes:
            - .:/app

    data_fetcher:
        image: ${DOCKER_USERNAME}/lmu-app-backend-data:${ENVIRONMENT}
        build:
            context: .
            dockerfile: docker/Dockerfile-data_fetcher
            args:
                BUILD_ENV: ${ENVIRONMENT:-development}
                COMMIT_SHA: local
                BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
        env_file:
            - .env
        container_name: data_fetcher
        networks:
            - shared
        environment:
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - ENVIRONMENT=${ENVIRONMENT:-development}
        restart: on-failure

    data_fetcher_dev:
        extends: data_fetcher
        container_name: data_fetcher_dev
        volumes:
            - .:/app

    nginx:
        container_name: nginx
        image: 'jc21/nginx-proxy-manager:2.12.3'
        restart: unless-stopped
        ports:
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
        volumes:
            - ./nginx/data:/data
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./nginx/snippets:/snippets:ro
        environment:
            TZ: 'Europe/Berlin'
        networks:
            - shared

volumes:
    postgres_data:
    postgres_metabase_data:

networks:
    shared:
        external: true
