FROM python:3.12-slim

#
WORKDIR /app


# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Only copy shared and api folders
COPY ./shared /app/shared
COPY ./api /app/api

# gets called in docker-compose.yml
# CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
