FROM python:3.12-slim

#
WORKDIR /app


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


COPY ./data_fetcher /app/data_fetcher

# run data_fetcher/main.py
CMD ["python", "data_fetcher/main.py"]
