from enum import Enum

class CanteenID(Enum):
    MENSA_ARCISSTR = "mensa-arcisstr"
    MENSA_GARCHING = "mensa-garching"
    MENSA_LEOPOLDSTR = "mensa-leopoldstr"
    MENSA_LOTHSTR = "mensa-lothstr"
    MENSA_MARTINSRIED = "mensa-martinsried"
    MENSA_PASING = "mensa-pasing"
    MENSA_WEIHENSTEPHAN = "mensa-weihenstephan"
    MEDIZINER_MENSA = "mediziner-mensa"
    STUBISTRO_ARCISSTR = "stubistro-arcisstr"
    STUBISTRO_GOETHESTR = "stubistro-goethestr"
    STUBISTRO_BUTENANDSTR = "stubistro-butenandstr"
    STUBISTRO_ROSENHEIM = "stubistro-rosenheim"
    STUBISTRO_SCHELLINGSTR = "stubistro-schellingstr"
    STUBISTRO_MARTINSRIED = "stubistro-martinsried"
    STUCAFE_ADALBERTSTR = "stucafe-adalbertstr"
    STUCAFE_AKADEMIE_WEIHENSTEPHAN = "stucafe-akademie-weihenstephan"
    STUCAFE_WEIHENSTEPHAN_MAXIMUS = "stucafe-weihenstephan-maximus"
    STUCAFE_BOLTZMANNSTR = "stucafe-boltzmannstr"
    STUCAFE_GARCHING = "stucafe-garching"
    STUCAFE_KARLSTR = "stucafe-karlstr"
    STUCAFE_PASING = "stucafe-pasing"
    FMI_BISTRO = "fmi-bistro"
    IPP_BISTRO = "ipp-bistro"
    # MENSA_BILDUNGSCAMPUS_HEILBRONN = "mensa-bildungscampus-heilbronn"
    # MENSA_STRAUBING = "mensa-straubing"
