"""auto

Revision ID: 2eb6ccc55673
Revises: 3268c5b0755b
Create Date: 2025-01-13 17:39:06.770007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb6ccc55673'
down_revision: Union[str, None] = '3268c5b0755b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.alter_column('canteen_likes', 'canteen_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'canteen_likes', 'canteens', ['canteen_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'canteen_likes', type_='foreignkey')
    op.alter_column('canteen_likes', 'canteen_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('canteen_opening_hours')
    # ### end Alembic commands ###
