"""auto

Revision ID: 5bc5625056d0
Revises: 
Create Date: 2025-01-16 15:13:40.102414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc5625056d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('app_version', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('system_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'system_version')
    op.drop_column('feedback', 'app_version')
    # ### end Alembic commands ###
