"""auto

Revision ID: 5f2271e93fc5
Revises: 
Create Date: 2025-04-14 19:04:53.521873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f2271e93fc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_translations')
    op.drop_table('device_tokens')
    op.drop_table('benefit_translations')
    op.drop_table('notifications')
    op.drop_table('benefits')
    op.create_foreign_key(None, 'buildings', 'streets', ['street_id'], ['id'])
    op.create_foreign_key(None, 'rooms', 'floors', ['floor_id'], ['id'])
    op.alter_column('sport_course_location', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sport_course_location', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.create_table('benefits',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='benefits_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('benefit_translations',
    sa.Column('benefit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], name='benefit_translations_benefit_id_fkey'),
    sa.PrimaryKeyConstraint('benefit_id', 'language', name='benefit_translations_pkey')
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='device_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='device_tokens_pkey'),
    sa.UniqueConstraint('token', name='device_tokens_token_key')
    )
    op.create_table('notification_translations',
    sa.Column('notification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name='notification_translations_notification_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', 'language', name='notification_translations_pkey')
    )
    # ### end Alembic commands ###
