"""device id nullable

Revision ID: 64d6353b80e1
Revises: c6502cecec69
Create Date: 2024-12-30 16:00:48.484120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d6353b80e1'
down_revision: Union[str, None] = 'c6502cecec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'canteen_images', 'canteens', ['canteen_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'canteen_locations', 'canteens', ['canteen_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'canteen_opening_hours', 'canteens', ['canteen_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cinema_locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cinema_locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'dish_likes', 'dishes', ['dish_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dish_prices', 'dishes', ['dish_id'], ['id'], ondelete='CASCADE')
    op.alter_column('feedback', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'menu_dish_associations', 'dishes', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'movie_genre_associations', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'movie_genre_associations', type_='foreignkey')
    op.drop_constraint(None, 'menu_dish_associations', type_='foreignkey')
    op.alter_column('feedback', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'dish_prices', type_='foreignkey')
    op.drop_constraint(None, 'dish_likes', type_='foreignkey')
    op.alter_column('cinema_locations', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cinema_locations', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(None, 'canteen_opening_hours', type_='foreignkey')
    op.drop_constraint(None, 'canteen_locations', type_='foreignkey')
    op.drop_constraint(None, 'canteen_images', type_='foreignkey')
    # ### end Alembic commands ###
