"""auto

Revision ID: 6b602622d099
Revises:
Create Date: 2025-04-19 20:45:22.545206

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b602622d099"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("link_benefits", sa.Column("types", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("link_benefits", sa.Column("faculties", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("link_resources", sa.Column("faculties", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("link_resources", "faculties")
    op.drop_column("link_benefits", "faculties")
    op.drop_column("link_benefits", "types")
    # ### end Alembic commands ###
