"""Initial migration

Revision ID: b078ef6cfc23
Revises: 
Create Date: 2024-11-20 13:06:53.502004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b078ef6cfc23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteen_images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('canteen_images', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('wishlist_images', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('wishlist_images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('wishlist_images', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist_images', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('wishlist_images', 'updated_at')
    op.drop_column('wishlist_images', 'created_at')
    op.alter_column('canteen_images', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('canteen_images', 'updated_at')
    # ### end Alembic commands ###
