FROM python:3.12-slim


WORKDIR /app

# install dependencies
COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

# Copy data_fetcher, shared, and api folders (api needed for GraphQL files)
COPY ./data_fetcher /app/data_fetcher
COPY ./shared /app/shared
COPY ./api /app/api


# run data_fetcher/main.py
CMD ["python", "data_fetcher/src/main.py"]