FROM python:3.12-slim

# Set environment argument with default value
ARG ENVIRONMENT=development
ENV ENVIRONMENT=${ENVIRONMENT}

WORKDIR /app

# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Only copy shared and api folders
COPY ./shared /app/shared
COPY ./api /app/api

# Copy appropriate environment file
COPY .env.${ENVIRONMENT} /app/.env

CMD ["uvicorn", "api.src.v1.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
