FROM python:3.12-slim

# Set environment argument with default value
ARG ENVIRONMENT=development
ENV ENVIRONMENT=${ENVIRONMENT}

WORKDIR /app

# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Only copy data_fetcher and shared folders
COPY ./data_fetcher /app/data_fetcher/src
COPY ./shared /app/shared/src

# Copy appropriate environment file
COPY .env.${ENVIRONMENT} /app/.env

# run data_fetcher/main.py
CMD ["python", "data_fetcher/src/main.py"]
