FROM python:3.12-slim


WORKDIR /app


# install dependencies
COPY requirements.txt ./
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

# Only copy shared and api folders
COPY ./shared /app/shared
COPY ./api /app/api
COPY ./alembic /app/alembic
COPY ./alembic.ini /app/alembic.ini


CMD ["uvicorn", "api.src.main:app", "--host", "0.0.0.0", "--port", "8000"]
