benefits_constants = [
    {
        "title": "Figma",
        "description": "Design, Prototyping, Real-Time Collaboration",
        "url": "https://www.figma.com/education/",
        "favicon_url": "https://icon.horse/icon/www.figma.com",
        "image_url": "https://strapi.dhiwise.com/uploads/618fa90c201104b94458e1fb_6326e73794be2a76df36cac6_11_Figma_Fundamental_1173_X486_0b62ca14be.jpg",
        "faculties": [],
        "types": ["SOFTWARE"],
        "aliases": ["design", "prototype", "collaborate", "interface", "wireframe", "mockup", "graphics"],
    },
    {
        "title": "Gärtnerplatz Theater",
        "description": "Discounted tickets for students",
        "url": "https://www.gaertnerplatztheater.de/de/seiten/angebote-fuer-studierende.html",
        "favicon_url": "https://icon.horse/icon/www.gaertnerplatztheater.de",
        "image_url": "https://www.gaertnerplatztheater.de/uploads/Foto_Video_Galerien/galerien/Haus/Theater_au%C3%9Fen/_10a9640-regpogozach.jpg?1780_750",
        "faculties": [],
        "types": ["CULTURE"],
        "aliases": ["student", "deals", "theater", "gaertnerplatz", "cheap", "reduced"],
    },
    {
        "title": "GitHub Education",
        "description": "Free GitHub Pro, Copilot, Codespaces, Student Developer Pack",
        "url": "https://github.com/education",
        "favicon_url": "https://icon.horse/icon/github.com",
        "image_url": "https://education.github.com/assets/pack/opengraph-image-c6d692948bb5fbf237b8a72d6576b4dcc84586335b522a6036904fc16ec7eccd.png",
        "faculties": [],
        "types": ["SOFTWARE"],
        "aliases": ["education", "student", "developer", "githubu", "codespaces", "copilot"],
    },
    {
        "title": "JetBrains",
        "description": "Free IDEs, IDE Extensions, and more",
        "url": "https://www.jetbrains.com/student/",
        "favicon_url": "https://icon.horse/icon/www.jetbrains.com",
        "image_url": "https://resources.jetbrains.com/storage/desktop-art/general/jetbrains/Wallpapers/1366x768-jetbrains2024_1.png",
        "faculties": [],
        "types": ["SOFTWARE"],
        "aliases": ["intellij", "pycharm", "webstorm", "rider", "clion", "phpstorm", "tools"],
    },
    {
        "title": "MVG Ermäßigungsticket",
        "description": "Discounted ticket for 38€ per month",
        "url": "https://www.mvg.de/abos-tickets/abos/ermaessigungsticket.html",
        "favicon_url": "https://icon.horse/icon/www.mvg.de",
        "image_url": "https://www.mvg.de/dam/jcr:86494fae-6133-41bc-ac01-ac8e4ab95c10/19268-MVG-29E-Ticket-Student-Headerbild-Landingpage-1920x1080_E01.jpg",
        "faculties": [],
        "types": ["TRANSPORT"],
        "aliases": ["discount", "monthly", "ticket", "reduction", "offer", "bargain"],
    },
    {
        "title": "News and Magazines",
        "description": "Free and current",
        "url": "https://emedien.ub.uni-muenchen.de/login?url=https://www.pressreader.com/",
        "favicon_url": "https://icon.horse/icon/emedien.ub.uni-muenchen.de",
        "image_url": None,
        "faculties": [],
        "types": ["CULTURE"],
        "aliases": ["articles", "journals", "bulletin", "current", "updates"],
    },
    {
        "title": "Munich Philharmoniker",
        "description": "Discounted tickets for students",
        "url": "https://www.mphil.de/",
        "favicon_url": "https://icon.horse/icon/www.mphil.de",
        "image_url": "https://www.mphil.de/fileadmin/_processed_/b/1/csm_Muenchner_Philharmoniker_credit_Tobias_Hase_4_84f85ba94a.jpg.webp",
        "faculties": [],
        "types": ["CULTURE"],
        "aliases": ["student", "deals", "cheap", "youth", "budget", "concessions"],
    },
    {
        "title": "Staatsoper",
        "description": "Discounted tickets for students",
        "url": "https://www.staatsoper.de/",
        "favicon_url": "https://icon.horse/icon/www.staatsoper.de",
        "image_url": "https://www.staatsoper.de/media/_processed_/9/8/csm_Stufenbar_20-08-2020_052_37d06a9c1f.png",
        "faculties": [],
        "types": ["CULTURE"],
        "aliases": ["opera", "vienna", "theatre", "culture", "performance", "music"],
    },
]
