from .canteen_enums import *
from .cinema_enums import *
from .dish_category_enums import *
from .image_format_enum import *
from .language_enums import *
from .opening_hours_enum import *
from .rating_enums import *
from .university_enums import *
from .weekday_enum import *
