from enum import Enum


class FacultyEnum(str, Enum):
    CATHOLIC_THEOLOGY = "CATHOLIC_THEOLOGY"
    PROTESTANT_THEOLOGY = "PROTESTANT_THEOLOGY"
    LAW = "LAW"
    BUSINESS_ADMIN = "BUSINESS_ADMIN"
    ECONOMICS = "ECONOMICS"
    MEDICINE = "MEDICINE"
    VETERINARY_MEDICINE = "VETERINARY_MEDICINE"
    HISTORY_ARTS = "HISTORY_ARTS"
    PHILOSOPHY = "PHILOSOPHY"
    PSYCHOLOGY_EDUCATION = "PSYCHOLOGY_EDUCATION"
    CULTURE_STUDIES = "CULTURE_STUDIES"
    LANGUAGES_LITERATURE = "LANGUAGES_LITERATURE"
    SOCIAL_SCIENCES = "SOCIAL_SCIENCES"
    MATH_INFO_STATS = "MATH_INFO_STATS"
    PHYSICS = "PHYSICS"
    CHEMISTRY_PHARMACY = "CHEMISTRY_PHARMACY"
    BIOLOGY = "BIOLOGY"
    GEOSCIENCES = "GEOSCIENCES"
