taste_profile = {
    "version":1,
    "presets": [
        {
          "enum_name": "VEGETARIAN",
          "text": {
            "DE": "Vegetarisch",
            "EN": "Vegetarian"
          },
          "emoji_abbreviation": "🥕",
          "exclude": [
            "POULTRY",
            "BEEF",
            "VEAL",
            "PORK",
            "LAMB",
            "WILD_MEAT",
            "FISH",
            "SHELLFISH"
          ]
        },
        {
          "enum_name": "VEGAN",
          "text": {
            "DE": "Vegan",
            "EN": "Vegan"
          },
          "emoji_abbreviation": "🌱",
          "exclude": [
            "POULTRY",
            "BEEF",
            "VEAL",
            "PORK",
            "LAMB",
            "WILD_MEAT",
            "FISH",
            "SHELLFISH",
            "MILK",
            "LACTOSE",
            "CHICKEN_EGGS"
          ]
        },
        {
          "enum_name": "PESCETARIAN",
          "text": {
            "DE": "Pescetarisch",
            "EN": "Pescetarian"
          },
          "emoji_abbreviation": "🐠",
          "exclude": [
            "POULTRY",
            "BEEF",
            "VEAL",
            "PORK",
            "LAMB",
            "WILD_MEAT"
          ]
        },
        {
          "enum_name": "GLUTENFREE",
          "text": {
            "DE": "Glutenfrei",
            "EN": "Gluten-Free"
          },
          "emoji_abbreviation": "🌾",
          "exclude": [
            "GLUTEN",
            "WHEAT",
            "RYE",
            "CEREAL",
            "BARLEY",
            "OAT",
            "SPELT",
            "HYBRIDS"
          ]
        },
      {
         "enum_name":"LACTOSEFREE",
        "text":{
            "DE":"Lactosefrei",
            "EN":"Lactose-Free"
          },
         "emoji_abbreviation":"🥛",
         "exclude":[
            "MILK",
            "LACTOSE"
         ]
      },
      # {
      #    "enum_name":"HALAL",
      #    "name":"Halal",
      #    "exclude":[
      #       "PORK",
      #       "ALCOHOL"
      #    ]
      # },
      # {
      #    "enum_name":"KOSHER",
      #    "name":"Kosher",
      #    "exclude":[
      #       "PORK",
      #       "SHELLFISH",
      #       "MOLLUSCS"
      #    ]
      # }
   ],
   "sorted_labels":[
      {
         "enum_category":"MEAT",
         "name":"Fleisch",
         "items":[
            {
               "enum_name":"POULTRY",
               "text":{
                  "DE":"Geflügel",
                  "EN":"Poultry"
               },
               "emoji_abbreviation":"🐔",
               "text_abbreviation":""
            },
            {
               "enum_name":"BEEF",
               "text":{
                  "DE":"Rinderfleisch",
                  "EN":"Beef"
               },
               "emoji_abbreviation":"🐮",
               "text_abbreviation":""
            },
            {
               "enum_name":"VEAL",
               "text":{
                  "DE":"Kalbsfleisch",
                  "EN":"Veal"
               },
               "emoji_abbreviation":"🐂",
               "text_abbreviation":""
            },
            {
               "enum_name":"PORK",
               "text":{
                  "DE":"Schweinefleisch",
                  "EN":"Pork"
               },
               "emoji_abbreviation":"🐷",
               "text_abbreviation":""
            },
            {
               "enum_name":"LAMB",
               "text":{
                  "DE":"Lammfleisch",
                  "EN":"Lamb"
               },
               "emoji_abbreviation":"🐑",
               "text_abbreviation":""
            },
            {
               "enum_name":"WILD_MEAT",
               "text":{
                  "DE":"Wildfleisch",
                  "EN":"Wild meat"
               },
               "emoji_abbreviation":"🐗",
               "text_abbreviation":""
            }
         ]
      },
      {
         "enum_category":"SEAFOOD",
         "name":"Fisch",
         "items":[
            {
               "enum_name":"FISH",
               "text":{
                  "DE":"Fisch",
                  "EN":"Fish"
               },
               "emoji_abbreviation":"🐠",
               "text_abbreviation":"D"
            },
            {
               "enum_name":"SHELLFISH",
               "text":{
                  "DE":"Krebstiere",
                  "EN":"Shellfish"
               },
               "emoji_abbreviation":"🦀",
               "text_abbreviation":"B"
            }
         ]
      },
      {
         "enum_category":"DAIRY",
         "name":"Milchprodukte",
         "items":[
            {
               "enum_name":"MILK",
               "text":{
                  "DE":"Milch",
                  "EN":"Milk"
               },
               "emoji_abbreviation":"🥛",
               "text_abbreviation":"G"
            },
            {
               "enum_name":"LACTOSE",
               "text":{
                  "DE":"Laktose",
                  "EN":"Lactose"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"La"
            },
            {
               "enum_name":"CHICKEN_EGGS",
               "text":{
                  "DE":"Eier",
                  "EN":"Egg"
               },
               "emoji_abbreviation":"🥚",
               "text_abbreviation":"C"
            }
         ]
      },
      {
         "enum_category":"GLUTEN",
         "name":"Gluten",
         "items":[
            {
               "enum_name":"GLUTEN",
               "text":{
                  "DE":"Gluten",
                  "EN":"Gluten Containing Cereals"
               },
               "emoji_abbreviation":"🥖",
               "text_abbreviation":"A"
            },
            {
               "enum_name":"WHEAT",
               "text":{
                  "DE":"Weizen",
                  "EN":"Wheat"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"GlW"
            },
            {
               "enum_name":"CEREAL",
               "text":{
                  "DE":"Getreide",
                  "EN":"Cereal"
               },
               "emoji_abbreviation":"🌾",
               "text_abbreviation":""
            },
            {
               "enum_name":"RYE",
               "text":{
                  "DE":"Roggen",
                  "EN":"Rye"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"GlR"
            },
            {
               "enum_name":"BARLEY",
               "text":{
                  "DE":"Gerste",
                  "EN":"Barley"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"GlG"
            },
            {
               "enum_name":"OAT",
               "text":{
                  "DE":"Hafer",
                  "EN":"Oat"
               },
               "emoji_abbreviation":"🥣",
               "text_abbreviation":"GlH"
            },
            {
               "enum_name":"SPELT",
               "text":{
                  "DE":"Dinkel",
                  "EN":"Spelt"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"GlD"
            }
         ]
      },
      {
         "enum_category":"NUTS",
         "name":"Nüsse",
         "items":[
            {
               "enum_name":"PEANUTS",
               "text":{
                  "DE":"Erdnüsse",
                  "EN":"Peanut"
               },
               "emoji_abbreviation":"🥜",
               "text_abbreviation":"E"
            },
            {
               "enum_name":"ALMONDS",
               "text":{
                  "DE":"Mandeln",
                  "EN":"Almonds"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScM"
            },
            {
               "enum_name":"HAZELNUTS",
               "text":{
                  "DE":"Haselnüsse",
                  "EN":"Hazelnuts"
               },
               "emoji_abbreviation":"🌰",
               "text_abbreviation":"ScH"
            },
            {
               "enum_name":"WALNUTS",
               "text":{
                  "DE":"Walnüsse",
                  "EN":"Walnuts"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScW"
            },
            {
               "enum_name":"CASHEWS",
               "text":{
                  "DE":"Cashewnüsse",
                  "EN":"Cashews"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScC"
            },
            {
               "enum_name":"PECAN",
               "text":{
                  "DE":"Pekanüsse",
                  "EN":"Pecans"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScP"
            },
            {
               "enum_name":"PISTACHIOES",
               "text":{
                  "DE":"Pistazien",
                  "EN":"Pistachios"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScP"
            },
            {
               "enum_name":"MACADAMIA",
               "text":{
                  "DE":"Macadamianüsse",
                  "EN":"Macadamias"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"ScMa"
            },
            {
               "enum_name":"SESAME",
               "text":{
                  "DE":"Sesam",
                  "EN":"Sesame"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"K"
            }
         ]
      },
      {
         "enum_category":"ADDITIVES",
         "name":"Zusatzstoffe",
         "items":[
            {
               "enum_name":"SWEETENERS",
               "text":{
                  "DE":"Süßungsmittel",
                  "EN":"Sweeteners"
               },
               "emoji_abbreviation":"🍬",
               "text_abbreviation":"11"
            },
            {
               "enum_name":"FLAVOR_ENHANCER",
               "text":{
                  "DE":"Geschmacksverstärker",
                  "EN":"Flavor Enhancer"
               },
               "emoji_abbreviation":"🔬",
               "text_abbreviation":"4"
            },
            {
               "enum_name":"DYESTUFF",
               "text":{
                  "DE":"Farbstoffe",
                  "EN":"Dyestuff"
               },
               "emoji_abbreviation":"🎨",
               "text_abbreviation":"1"
            },
            {
               "enum_name":"PRESERVATIVES",
               "text":{
                  "DE":"Preservate",
                  "EN":"Preservatives"
               },
               "emoji_abbreviation":"🥫",
               "text_abbreviation":"2"
            },
            {
               "enum_name":"PHENYLALANINE",
               "text":{
                  "DE":"Phenylaline",
                  "EN":"Phenylalanine"
               },
               "emoji_abbreviation":"💊",
               "text_abbreviation":""
            },
            {
               "enum_name":"ANTIOXIDANTS",
               "text":{
                  "DE":"Antioxidanten",
                  "EN":"Antioxidants"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"3"
            }
         ]
      },
      {
         "enum_category":"MISCELLANEOUS",
         "name":"Sonstiges",
         "items":[
            {
               "enum_name":"SOY",
               "text":{
                  "DE":"Soja",
                  "EN":"Soy"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"F"
            },
            {
               "enum_name":"HYBRIDS",
               "text":{
                  "DE":"Hybridstämme",
                  "EN":"Hybrid Strains"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"GlHy"
            },
            {
               "enum_name":"CELERY",
               "text":{
                  "DE":"Sellerie",
                  "EN":"Celery"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"I"
            },
            {
               "enum_name":"MUSTARD",
               "text":{
                  "DE":"Senf",
                  "EN":"Mustard"
               },
               "emoji_abbreviation":"🌭",
               "text_abbreviation":"J"
            },
            {
               "enum_name":"SULPHURS",
               "text":{
                  "DE":"Schwefeldioxid",
                  "EN":"Sulphurs"
               },
               "emoji_abbreviation":"🔻",
               "text_abbreviation":"L"
            },
            {
               "enum_name":"SULFITES",
               "text":{
                  "DE":"Sulfite",
                  "EN":"Sulfites"
               },
               "emoji_abbreviation":"🔺",
               "text_abbreviation":"L"
            },
            {
               "enum_name":"LUPIN",
               "text":{
                  "DE":"Lupine",
                  "EN":"Lupin"
               },
               "emoji_abbreviation":"",
               "text_abbreviation":"M"
            },
            {
               "enum_name":"MOLLUSCS",
               "text":{
                  "DE":"Weichtiere",
                  "EN":"Molluscs"
               },
               "emoji_abbreviation":"🐙",
               "text_abbreviation":"N"
            },
            {
               "enum_name":"SHELL_FRUITS",
               "text":{
                  "DE":"Schalenfrüchte",
                  "EN":"Shell Fruits"
               },
               "emoji_abbreviation":"🥥",
               "text_abbreviation":"H"
            },
            {
               "enum_name":"WAXED",
               "text":{
                  "DE":"Gewachst",
                  "EN":"Waxed"
               },
               "emoji_abbreviation":"🐝",
               "text_abbreviation":"13"
            },
            {
               "enum_name":"PHOSPATES",
               "text":{
                  "DE":"Phosphate",
                  "EN":"Phosphates"
               },
               "emoji_abbreviation":"🔷",
               "text_abbreviation":"7"
            },
            {
               "enum_name":"COCOA_CONTAINING_GREASE",
               "text":{
                  "DE":"Kakaohaltiges Fett",
                  "EN":"Cocoa Containing Grease"
               },
               "emoji_abbreviation":"🍫",
               "text_abbreviation":""
            },
            {
               "enum_name":"GELATIN",
               "text":{
                  "DE":"Gelatine",
                  "EN":"Gelatin"
               },
               "emoji_abbreviation":"🍮",
               "text_abbreviation":""
            },
            {
               "enum_name":"ALCOHOL",
               "text":{
                  "DE":"Alkohol",
                  "EN":"Alcohol"
               },
               "emoji_abbreviation":"🍷",
               "text_abbreviation":""
            },
            {
               "enum_name":"GARLIC",
               "text":{
                  "DE":"Knoblauch",
                  "EN":"Garlic"
               },
               "emoji_abbreviation":"🧄",
               "text_abbreviation":""
            },
            {
               "enum_name":"BAVARIA",
               "text":{
                  "DE":"Zertifizierte Qualität Bayern",
                  "EN":"Certified Quality Bavaria"
               },
               "emoji_abbreviation":"🥨",
               "text_abbreviation":""
            },
            {
               "enum_name":"MSC",
               "text":{
                  "DE":"Marine Stewardship Council",
                  "EN":"Marine Stewardship Council"
               },
               "emoji_abbreviation":"🎣",
               "text_abbreviation":""
            }
         ]
      }
   ]
}